### PR TITLE
Allow webpack 2.1.x beta

### PR DESCRIPTION
**Pull request by benadamstyles**
... which I have confirmed as working correctly with `roots-webpack`

### CODE REVIEW

**Comment by jescalan** [comment]
👍 thank you!

**Comment by benadamstyles** [comment]
@jescalan Any chance you could publish a new version with this change?

**Comment by jescalan** [comment]
Absolutely! I'll have it live in a moment

**Comment by benadamstyles** [comment]
Amazing, thanks man

**Comment by jescalan** [comment]
Published!

**Pull request merged**
