### PR TITLE
Allow webpack 2.2.x

### PR DESCRIPTION
**Pull request by benadamstyles**
I know this is really ugly but I can't think of a better way, until they release v2 properly!

### CODE REVIEW

**Comment by jescalan** [comment]
So apparently we're looking at a full `2.x` release this week!

**Comment by benadamstyles** [comment]
Thanks again for such a quick response! I guess I will have another PR for you when they release...

**Comment by benadamstyles** [comment]
Any chance you could publish this to a new version?

**Comment by jescalan** [comment]
Hey, sorry for the delay, yes I'll do this now!

**Pull request merged**
