### PR TITLE
Make it work

### PR DESCRIPTION
**Pull request by hhsnopek**
TODO:
- [x] test against expected output
- [x] verify that multiple `webpack watchers` aren't being created

I'm unsure if this will actually work during `roots watch`. I don't believe it's actually accessing the other instances' variable `initialize`.

### CODE REVIEW

**Comment by hhsnopek** [comment]
excuse the commit name, had to make it build on travis haha

**Comment by hhsnopek** [comment]
lemme know what you think @jenius

**Comment by kylemac** [comment]
@hhsnopek any room to improve the tests while @jenius sleeps in grenada?

**Comment by hhsnopek** [comment]
Definitely can do that

## 

Henry Snopek

**Comment by hhsnopek** [comment]
**moved todo to description**

**Comment by hhsnopek** [comment]
Ready to be reviewed for rebase & merge
cc @jenius @kylemac

**Comment by kylemac** [comment]
going to let @jenius handle this PR as he had the vision for the original implementation

**Comment by jescalan** [comment]
Ok this looks good. I'm going to merge then pull down and do a little more testing to make sure we're set.

**Comment by hhsnopek** [comment]
awesome :)

**Pull request merged**
